project:
  type: website
  output-dir: ../assets/blog_site

website:
  title: ""  # Removes "My Project Blog" text in top-left
  navbar:
    left:
      - text: Home
        href: ../../index.html  # Adjust path if index.html is in project root

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: true
    self-contained: true
    mathjax: true
    code-fold: true
    code-summary: "Show Code"
    code-tools: true
    polyfill: false
    lib-dir: lib

execute:
  echo: true
  warning: false
  message: false
  error: false
  cache: true
